import {
  Activity,
  AlarmClock,
  Apple,
  Bandage,
  Bed,
  Bell,
  Bike,
  Bird,
  Banana,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bus,
  Calendar,
  Camera,
  Car,
  Carrot,
  Cat,
  Cherry,
  Clock,
  Code,
  Coffee,
  Coins,
  Compass,
  Cookie,
  Crown,
  Dog,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  Film,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Home,
  Key,
  Lamp,
  Laptop,
  Leaf,
  LeafyGreen,
  Library,
  Lightbulb,
  ListChecks,
  Luggage,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Palette,
  PenLine,
  PenTool,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Rocket,
  Scissors,
  Shield,
  ShoppingBag,
  ShowerHead,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  Terminal,
  Train,
  Trophy,
  TreePine,
  Tv,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const HABIT_ICON_IDS = [
  "activity",
  "footprints",
  "dumbbell",
  "bike",
  "waves",
  "zap",
  "flame",
  "trophy",
  "target",
  "medal",
  "heart",
  "pill",
  "stethoscope",
  "bandage",
  "smile",
  "eye",
  "ear",
  "brain",
  "apple",
  "carrot",
  "banana",
  "cherry",
  "egg",
  "cookie",
  "pizza",
  "utensils",
  "wine",
  "glass-water",
  "coffee",
  "droplets",
  "leaf",
  "sprout",
  "leafy-green",
  "tree-pine",
  "flower-2",
  "mountain",
  "sun",
  "moon",
  "book-open",
  "book-marked",
  "library",
  "graduation-cap",
  "lightbulb",
  "microscope",
  "notebook",
  "pen-line",
  "pencil",
  "newspaper",
  "music",
  "headphones",
  "mic",
  "film",
  "tv",
  "camera",
  "palette",
  "pen-tool",
  "scissors",
  "briefcase",
  "laptop",
  "terminal",
  "code",
  "calendar",
  "clock",
  "alarm-clock",
  "list-checks",
  "home",
  "bed",
  "shower-head",
  "brush",
  "lamp",
  "key",
  "users",
  "message-circle",
  "phone",
  "mail",
  "handshake",
  "compass",
  "dog",
  "cat",
  "bird",
  "plane",
  "car",
  "train",
  "bus",
  "map-pin",
  "luggage",
  "wallet",
  "piggy-bank",
  "coins",
  "shopping-bag",
  "gift",
  "sparkles",
  "star",
  "gamepad-2",
  "gem",
  "crown",
  "shield",
  "bell",
  "globe",
  "rocket",
] as const;

export type HabitIconId = (typeof HABIT_ICON_IDS)[number];

const ICON_MAP: Record<HabitIconId, LucideIcon> = {
  activity: Activity,
  footprints: Footprints,
  dumbbell: Dumbbell,
  bike: Bike,
  waves: Waves,
  zap: Zap,
  flame: Flame,
  trophy: Trophy,
  target: Target,
  medal: Medal,
  heart: Heart,
  pill: Pill,
  stethoscope: Stethoscope,
  bandage: Bandage,
  smile: Smile,
  eye: Eye,
  ear: Ear,
  brain: Brain,
  apple: Apple,
  carrot: Carrot,
  banana: Banana,
  cherry: Cherry,
  egg: Egg,
  cookie: Cookie,
  pizza: Pizza,
  utensils: Utensils,
  wine: Wine,
  "glass-water": GlassWater,
  coffee: Coffee,
  droplets: Droplets,
  leaf: Leaf,
  sprout: Sprout,
  "leafy-green": LeafyGreen,
  "tree-pine": TreePine,
  "flower-2": Flower2,
  mountain: Mountain,
  sun: Sun,
  moon: Moon,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  library: Library,
  "graduation-cap": GraduationCap,
  lightbulb: Lightbulb,
  microscope: Microscope,
  notebook: Notebook,
  "pen-line": PenLine,
  pencil: Pencil,
  newspaper: Newspaper,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  film: Film,
  tv: Tv,
  camera: Camera,
  palette: Palette,
  "pen-tool": PenTool,
  scissors: Scissors,
  briefcase: Briefcase,
  laptop: Laptop,
  terminal: Terminal,
  code: Code,
  calendar: Calendar,
  clock: Clock,
  "alarm-clock": AlarmClock,
  "list-checks": ListChecks,
  home: Home,
  bed: Bed,
  "shower-head": ShowerHead,
  brush: Brush,
  lamp: Lamp,
  key: Key,
  users: Users,
  "message-circle": MessageCircle,
  phone: Phone,
  mail: Mail,
  handshake: Handshake,
  compass: Compass,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  plane: Plane,
  car: Car,
  train: Train,
  bus: Bus,
  "map-pin": MapPin,
  luggage: Luggage,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  coins: Coins,
  "shopping-bag": ShoppingBag,
  gift: Gift,
  sparkles: Sparkles,
  star: Star,
  "gamepad-2": Gamepad2,
  gem: Gem,
  crown: Crown,
  shield: Shield,
  bell: Bell,
  globe: Globe,
  rocket: Rocket,
};

export function isHabitIconId(value: string): value is HabitIconId {
  return (HABIT_ICON_IDS as readonly string[]).includes(value);
}

export function getHabitIconComponent(iconId: string): LucideIcon {
  if (isHabitIconId(iconId)) {
    return ICON_MAP[iconId];
  }
  return Activity;
}

export const DEFAULT_HABIT_ICON: HabitIconId = "activity";
